Install-windowsfeature -Name `
File-Services, `
FS-FileServer, `
FS-Data-Deduplication, `
FS-iSCSITarget-Server, `
FS-NFS-Service, `
Hyper-V, `
BitLocker, `
Data-Center-Bridging, `
EnhancedStorage, `
Failover-Clustering, `
RSAT-Feature-Tools-BitLocker, `
RSAT-Feature-Tools-BitLocker-RemoteAdminTool, `
RSAT-Feature-Tools-BitLocker-BdeAducExt, `
RSAT-DataCenterBridging-LLDP-Tools, `
RSAT-Clustering, `
RSAT-Clustering-Mgmt, `
RSAT-Clustering-PowerShell, `
RSAT-Storage-Replica, `
RSAT-Role-Tools, `
RSAT-AD-Tools, `
RSAT-ADDS, `
RSAT-ADDS-Tools, `
RSAT-Hyper-V-Tools, `
Hyper-V-Tools, `
Hyper-V-PowerShell, `
RSAT-File-Services, `
RSAT-NFS-Admin, `
SNMP-WMI-Provider, `
Storage-Replica, `
Windows-Defender, `
Windows-Server-Backup `
-IncludeManagementTools -Restart